name: Deploy a GitHub Pages

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Reescribir base href
        uses: run: sed -i 's|<base href="/"|<base href="/FormatConverter/"|' frontend/FormatConverter.Frontend/wwwroot/index.html
        # with:
        #   working_directory: frontend/FormatConverter.Frontend/wwwroot
        #   base_href: /FormatConverter/

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Publicar
        run: dotnet publish frontend/FormatConverter.Frontend -c Release -o publish

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish/wwwroot

      - name: Desplegar en Pages
        id: deployment
        uses: actions/deploy-pages@v4